server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: 12345
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "a/Wyr5lSgfv9Gj0z12VUyCKSFjeSato9HkLsGuSo1bcT0sVMXY8Sr0Uzbrtt4px+"

logging:
  level:
    org.springframework.web: DEBUG

