server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: 12345
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1DphB90eCAa+E/MNGnxcyE3eTO4+Uzn5m1rtKNm27YHyLEb26PUy/2IV6+1JS2xC"

logging:
  level:
    org.springframework.web: DEBUG

